### ISSUE TITLE
切换城市问题

### ISSUE THREAD

**Issue by xxhh07** [CaiJingLong/flutter_city_picker#2]
在切换市的时候，区域不会切换，但是数据是可以返回的
比如：
安徽省 淮北市跟铜陵市 区域显示不会切换
福建省 泉州市跟三明市 区域显示不会切换，
数据返回是正确的

**Comment by CaiJingLong** [comment]
刚刚测试了下 确实有部分二级菜单和三级菜单不会联动 我查下原因

**Comment by CaiJingLong** [comment]
修复完成 更新0.1.1

**Comment by xxhh07** [comment]
> 修复完成 更新0.1.1

可以了，谢谢
