### ISSUE TITLE
插件包安装失败，错误信息如下

### ISSUE THREAD

**Issue by OmgKevin** [CaiJingLong/flutter_city_picker#5]
The current Dart SDK version is 2.1.0-dev.3.1.flutter-760a9690c2.

Because myapp depends on city_picker >=0.1.1 which requires SDK version >=2.1.0 <3.0.0, version solving failed.
 
pub get failed (1)

**Comment by CaiJingLong** [comment]
代码中有dart sdk的版本约束,因为用到了dart 2.1版本的api
低于这个约束的不保证代码可运行

解决方案
---
升级你的flutter sdk版本

**Comment by OmgKevin** [comment]
谢谢，问题已解决
